# Generated by Django 6.0.1 on 2026-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(default='', upload_to='category/'),
            preserve_default=False,
        ),
    ]
